version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql-native-password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: apirest
    ports:
      - 3308:3306
    networks:
      - aspnet-network

  rest_with_asp_net:
    image: rest_with_asp_net
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      TZ: America/Sao Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - aspnet-network

networks:
  aspnet-network:
    driver: bridge