version: '3.4'

services:
  rest_with_asp_net:
    image: rest_with_asp_net
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      TZ: America/Sao Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5001:80
    networks:
      - aspnet-network

networks:
  aspnet-network:
    driver: bridge
